### ISSUE TITLE
HospitalizedNumberCardで「入院」と「宿泊療養」を分けて表示する

### ISSUE THREAD

**Issue by suzuryo** [MeditationDuck/covid19#763]
## 関連する
- #758

## 改善詳細 / Details of Improvement
- 入院と宿泊療養の合計が表示されている
- 検査実施件数の「PCR検査実施件数」と「抗原検査件数」のように、「入院」と「宿泊」を分けて表示する

## TODO
- [x] positive_status.json の hospitalized が 「うち入院中」と「うち宿泊療養中」の合計になっているので項目を分ける
- [x] HospitalizedNumberCard.vue で 「入院」と「宿泊」の項目を積み上げグラフで表示する
- [x] HospitalizedNumberCard.vue の 「テーブル」も「入院」と「宿泊」の項目が別れていること
- [ ] データテーブルには「合計」も表示したい
